### ISSUE TITLE
Create the Kotlin endpoint

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/coding_challenge-28#5]
## **❗ IMPORTANT:** 
👁️‍🗨️ Check no one has claimed this task in the comments!
✏️ Claim this task by stating you are working on it in the comments.
> To ensure people have a chance to complete their task, PRs only be accepted from the first person that claimed the task. If you believe the task is stagnant, mention @MattCSmith, @notAnkur or @thisisabdus is the comments for review. 

## 📚 **User Story**
> I would like to be able to view general details about the kotlin language, at the endpoint `/v1/languages/kotlin/`

## ✔️ **Acceptance Criteria**

- [ ] Fill out as many of the fields you can or want to
- [ ] Ensuring incomplete/unknown fields contain `{{UNKNOWN}}`
- [ ] Run `yarn test` or `npm test` and fix any errors. 
- [ ] Create a PR which includes this issues's URL and detail its completeness

### Creating the general language file: 
First we need to create the directory and file for the general language details endpoint, we do this by:
1. Creating a directory named `kotlin` inside `/json/languages/`
2. Creating a file named `kotlin.js` inside `/json/languages/kotlin/`
3. Using the **Example Language JSON** below to create this file, fill out as many of the fields as you can manage, ensuring incomplete or unknown fields contain `{{UNKNOWN}}`.

### Testing: 
We now must run the tests to ensure that there are no issues in any of the JSON we have just written. You can do this by running: `yarn test` or `npm test`. Fixing any issue that pops up. PRs that fail testing cannot be merged and must be resolved first. If you get stuck, reach out in the comments or on Discord. 

## 🖥️ **Example Language JSON**
```js
const kotlin = {
  name: '{{UNKNOWN}}',
  description_short: '{{UNKNOWN}}',
  description: '{{UNKNOWN}}',
  paradigm: ['{{UNKNOWN}}'],
  developed_by: [
    {
      name: '{{UNKNOWN}}',
      endpoint: '{{UNKNOWN}}',
      website: '{{UNKNOWN}}',
      twitter: '{{UNKNOWN}}'
    }
  ],
  first_appeared: '{{UNKNOWN}}',
  version: {
    current_stable: {
      version_name: '{{UNKNOWN}}',
      code_name: '{{UNKNOWN}}',
      release_data: '{{UNKNOWN}}'
    },
    upcoming_version: {
      version_name: '{{UNKNOWN}}',
      code_name: '{{UNKNOWN}}',
      expected_release_date: '{{UNKNOWN}}'
    },
    all_versions: [
      {
        version_name: '{{UNKNOWN}}',
        code_name: '{{UNKNOWN}}',
        release_date: '{{UNKNOWN}}'
      },
    ],
  },
  typing_discipline: ['{{UNKNOWN}}'],
  platform: ['{{unknown}}'],
  operating_system: ['{{unknown}}'],
  license: ['{{unknown}}'],
  example_snippets: {
    hello_world: '{{UNKNOWN}}',
  },
};

module.exports = kotlin;
```

**Comment by mahendra1290** [comment]
i would like to this task

**Comment by notAnkur** [comment]
Sorry there's no api directory. Just edited the issue.

**Comment by mahendra1290** [comment]
Thanks @notAnkur

**Comment by mahendra1290** [comment]
In the **Acceptance Criteria** block it has been said to create `/v1/languages/kotlin/kotlin.js `using **Example Language JSON** and in 
**How To**  it says to create` /json/languages/kotlin/kotlin.js` using **Example Language JSON**
What we have to do ??
I think the we have to follow **How To** because their  are routes  files in `/v1/languages/`
can you please clear my doubt

**Comment by notAnkur** [comment]
Removed the one in **Acceptance Criteria**. Thanks :)

**Comment by mahendra1290** [comment]
Thanks Again :)
