### ISSUE TITLE
Create the Go endpoint

### ISSUE THREAD

**Issue by MattCSmith** [zero-to-mastery/coding_challenge-28#6]
## **❗ IMPORTANT:** 
👁️‍🗨️ Check no one has claimed this task in the comments!
✏️ Claim this task by stating you are working on it in the comments.
> To ensure people have a chance to complete their task, PRs only be accepted from the first person that claimed the task. If you believe the task is stagnant, mention @MattCSmith, @notAnkur or @thisisabdus is the comments for review. 

## 📚 **User Story**
> I would like to be able to view general details about the go language, at the endpoint `/v1/languages/go/`

## ✔️ **Acceptance Criteria**

- [ ] Fill out as many of the fields you can or want to
- [ ] Ensuring incomplete/unknown fields contain `{{UNKNOWN}}`
- [ ] Run `yarn test` or `npm test` and fix any errors. 
- [ ] Create a PR which includes this issues's URL and detail its completeness

### Creating the general language file: 
First we need to create the directory and file for the general language details endpoint, we do this by:
1. Creating a directory named `go` inside `/json/languages/`
2. Creating a file named `go.js` inside `/json/languages/go/`
3. Using the **Example Language JSON** below to create this file, fill out as many of the fields as you can manage, ensuring incomplete or unknown fields contain `{{UNKNOWN}}`.

### Testing: 
We now must run the tests to ensure that there are no issues in any of the JSON we have just written. You can do this by running: `yarn test` or `npm test`. Fixing any issue that pops up. PRs that fail testing cannot be merged and must be resolved first. If you get stuck, reach out in the comments or on Discord. 

## 🖥️ **Example Language JSON**
```js
const go = {
  name: '{{UNKNOWN}}',
  description_short: '{{UNKNOWN}}',
  description: '{{UNKNOWN}}',
  paradigm: ['{{UNKNOWN}}'],
  developed_by: [
    {
      name: '{{UNKNOWN}}',
      endpoint: '{{UNKNOWN}}',
      website: '{{UNKNOWN}}',
      twitter: '{{UNKNOWN}}'
    }
  ],
  first_appeared: '{{UNKNOWN}}',
  version: {
    current_stable: {
      version_name: '{{UNKNOWN}}',
      code_name: '{{UNKNOWN}}',
      release_data: '{{UNKNOWN}}'
    },
    upcoming_version: {
      version_name: '{{UNKNOWN}}',
      code_name: '{{UNKNOWN}}',
      expected_release_date: '{{UNKNOWN}}'
    },
    all_versions: [
      {
        version_name: '{{UNKNOWN}}',
        code_name: '{{UNKNOWN}}',
        release_date: '{{UNKNOWN}}'
      },
    ],
  },
  typing_discipline: ['{{UNKNOWN}}'],
  platform: ['{{unknown}}'],
  operating_system: ['{{unknown}}'],
  license: ['{{unknown}}'],
  example_snippets: {
    hello_world: '{{UNKNOWN}}',
  },
};

module.exports = go;
```

**Comment by lukaszwisniewski88** [comment]
I will work on this one. Today evening will make an PR on this.
